//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTESMENSUALES
    {
        public int IdReporte { get; set; }
        public int IdComercio { get; set; }
        public int CantidadDeCajas { get; set; }
        public int MontoTotalRecaudado { get; set; }
        public int CantidadDeSinpes { get; set; }
        public decimal MontoTotalComision { get; set; }
        public System.DateTime FechaDelReporte { get; set; }
    
        public virtual COMERCIO COMERCIO { get; set; }
    }
}
