//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataFormaDePagosWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACION_DE_COMERCIO
    {
        public int idConfiguracion { get; set; }
        public Nullable<int> IdComercio { get; set; }
        public int TipoConfiguracion { get; set; }
        public int Comision { get; set; }
        public System.DateTime FechaDeRegistro { get; set; }
        public System.DateTime FechaDeModificacion { get; set; }
        public bool Estado { get; set; }
    
        public virtual COMERCIO COMERCIO { get; set; }
    }
}
