//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataFormaDePagosWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACION_DE_COMERCIO
    {
        public int idConfiguracion { get; set; }
        public Nullable<int> IdComercio { get; set; }
        public int TipoConfiguracion { get; set; }
        public int Comision { get; set; }
        public System.DateTime FechaDeRegistro { get; set; }
        public System.DateTime FechaDeModificacion { get; set; }
        public bool Estado { get; set; }
    
        public virtual COMERCIO COMERCIO { get; set; }
    }
}
