//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataFormaDePagosWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROYECTO_BANCO_LOS_PATITOSEntities : DbContext
    {
        public PROYECTO_BANCO_LOS_PATITOSEntities()
            : base("name=PROYECTO_BANCO_LOS_PATITOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BITACORA> BITACORA { get; set; }
        public virtual DbSet<CAJA> CAJA { get; set; }
        public virtual DbSet<COMERCIO> COMERCIO { get; set; }
        public virtual DbSet<SINPE> SINPE { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<CONFIGURACION_DE_COMERCIO> CONFIGURACION_DE_COMERCIO { get; set; }
    }
}
