//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataFormaDePagosWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROYECTO_BANCO_LOS_PATITOSEntities : DbContext
    {
        public PROYECTO_BANCO_LOS_PATITOSEntities()
            : base("name=PROYECTO_BANCO_LOS_PATITOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BITACORA> BITACORA { get; set; }
        public virtual DbSet<CAJA> CAJA { get; set; }
        public virtual DbSet<COMERCIO> COMERCIO { get; set; }
        public virtual DbSet<SINPE> SINPE { get; set; }
        public virtual DbSet<CONFIGURACION_DE_COMERCIO> CONFIGURACION_DE_COMERCIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<REPORTESMENSUALES> REPORTESMENSUALES { get; set; }
    }
}
