//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataFormaDePagosWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTESMENSUALES
    {
        public int IdReporte { get; set; }
        public int IdComercio { get; set; }
        public int CantidadDeCajas { get; set; }
        public int MontoTotalRecaudado { get; set; }
        public int CantidadDeSinpes { get; set; }
        public decimal MontoTotalComision { get; set; }
        public System.DateTime FechaDelReporte { get; set; }
    
        public virtual COMERCIO COMERCIO { get; set; }
    }
}
