//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataFormaDePagosWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINPE
    {
        public int IdSinpe { get; set; }
        public string TelefonoOrigen { get; set; }
        public string NombreOrigen { get; set; }
        public string TelefonoDestinatario { get; set; }
        public string NombreDestinatario { get; set; }
        public decimal Monto { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaDeRegistro { get; set; }
        public Nullable<System.DateTime> FechaDeModificacion { get; set; }
        public bool Estado { get; set; }
    }
}
