//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataFormaDePagosWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINPE
    {
        public int IdSinpe { get; set; }
        public string TelefonoOrigen { get; set; }
        public string NombreOrigen { get; set; }
        public string TelefonoDestinatario { get; set; }
        public string NombreDestinatario { get; set; }
        public decimal Monto { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaDeRegistro { get; set; }
        public Nullable<System.DateTime> FechaDeModificacion { get; set; }
        public bool Estado { get; set; }
    }
}
