//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataFormaDePagosWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int IdUsuario { get; set; }
        public Nullable<int> IdComercio { get; set; }
        public Nullable<System.Guid> IdNetUser { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Identificación { get; set; }
        public string CorreoElectronico { get; set; }
        public System.DateTime FechaDeRegistro { get; set; }
        public System.DateTime FechaDeModificacion { get; set; }
        public bool Estado { get; set; }
    
        public virtual COMERCIO COMERCIO { get; set; }
    }
}
